### ISSUE TITLE
Unhandled exception executing command 'heimdall' in plugin Heimdall v0.7.2

### ISSUE THREAD

**Issue by fungreenfox** [andune/heimdall#3]
I have just installed this, and the first i do, is typing /heimdall and getting this:

00:53:51 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'heimdall' in plugin Heimdall v0.7.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:189)
        at org.bukkit.craftbukkit.v1_5_R2.CraftServer.dispatchCommand(CraftServer.java:523)
        at net.minecraft.server.v1_5_R2.PlayerConnection.handleCommand(PlayerConnection.java:966)
        at net.minecraft.server.v1_5_R2.PlayerConnection.chat(PlayerConnection.java:884)
        at net.minecraft.server.v1_5_R2.PlayerConnection.a(PlayerConnection.java:841)
        at net.minecraft.server.v1_5_R2.Packet3Chat.handle(Packet3Chat.java:44)
        at net.minecraft.server.v1_5_R2.NetworkManager.b(NetworkManager.java:292)
        at net.minecraft.server.v1_5_R2.PlayerConnection.d(PlayerConnection.java:110)
        at net.minecraft.server.v1_5_R2.ServerConnection.b(SourceFile:35)
        at net.minecraft.server.v1_5_R2.DedicatedServerConnection.b(SourceFile:30)
        at net.minecraft.server.v1_5_R2.MinecraftServer.r(MinecraftServer.java:580)
        at net.minecraft.server.v1_5_R2.DedicatedServer.r(DedicatedServer.java:225)
        at net.minecraft.server.v1_5_R2.MinecraftServer.q(MinecraftServer.java:476)
        at net.minecraft.server.v1_5_R2.MinecraftServer.run(MinecraftServer.java:409)
        at net.minecraft.server.v1_5_R2.ThreadServerApplication.run(SourceFile:573)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
        at org.morganm.heimdall.commands.Heimdall.onCommand(Heimdall.java:29)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
        ... 15 more

This server is running CraftBukkit version git-Bukkit-1.5.1-R0.2-5-g7fd3e34-b2758jnks (MC: 1.5.1) (Implementing API version 1.5.1-R0.3-SNAPSHOT)

**Comment by andune** [comment]
Thanks, this is confirmed as bug. The arg check a few lines earlier should be <=, not <. Don't run the /heimdall command without any args to avoid this stack trace, until a new version is published to fix it. You can look at the source code to see the valid arguments this command accepts:

https://github.com/andune/heimdall/blob/master/src/main/java/org/morganm/heimdall/commands/Heimdall.java

**Comment by fungreenfox** [comment]
Have you planned on correcting this? ill have to uninstall because of logblock use is more important.

**Comment by andune** [comment]
This particular stack trace only happens when you type /heimdall command with no args and has no impact on how well LogBlock runs. If you have a stack trace related to LogBlock that is stopping LogBlock from working, I'd be very interested to see it. My server runs Heimdall and LogBlock and both work fine together.

**Comment by fungreenfox** [comment]
i think problem then is, that the users have access to see what happens ingame, and some of them cannot learn very fast, telling them to avoid typing that, is useless.
