### ISSUE TITLE
Processing enricher problem?

### ISSUE THREAD

**Issue by Leopere** [andune/heimdall#7]
20:31:40 [WARNING] [Heimdall] [Heimdall]  Caught exception processing event for enricher com.andune.heimdall.event.handlers.EngineWrapper@1fba9caf, error: Asynchronous entity world add!
java.lang.IllegalStateException: Asynchronous entity world add!
        at net.minecraft.server.v1_6_R2.World.a(World.java:2493)
        at net.minecraft.server.v1_6_R2.Chunk.addEntities(Chunk.java:683)
        at net.minecraft.server.v1_6_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:128)
        at net.minecraft.server.v1_6_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:84)
        at org.bukkit.craftbukkit.v1_6_R2.CraftWorld.getChunkAt(CraftWorld.java:119)
        at org.bukkit.craftbukkit.v1_6_R2.CraftWorld.getChunkAt(CraftWorld.java:497)
        at org.bukkit.Location.getChunk(Location.java:73)
        at com.andune.heimdall.engine.FriendEngine.processBlockChange(FriendEngine.java:77)
        at com.andune.heimdall.event.handlers.EngineWrapper.processEvent(EngineWrapper.java:60)
        at com.andune.heimdall.event.BlockChangeEvent.accept(BlockChangeEvent.java:135)
        at com.andune.heimdall.event.EventManager.run(EventManager.java:205)
        at org.bukkit.craftbukkit.v1_6_R2.scheduler.CraftTask.run(CraftTask.java:58)
        at org.bukkit.craftbukkit.v1_6_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:724)
20:31:52 [INFO] [Prism]: &7mahan14 found 4 iron ore 0% light

**Comment by andune** [comment]
You may be running a different version than the latest version I have checked in and available on the Jenkins server, which will make troubleshooting any error reports hard since line numbers don't match up.

However, looking in the same proximity of the line numbers here, I'm pretty sure I can guess the issue, which is that Heimdall processes its events asynchronously to avoid server lag from hitting the DB for owner lookups, but in turn it violates a Bukkit contract rule on occasion by calling back into the APIs asynchronously. It does NOT do any write activities to minimize the chance for conflict, but regardless it opens up the possibility for conflicts with plugins that DO async write or even Bukkit itself under the right circumstances.

The correct thing to do would be to do the time-sensitive processing on async and then push any sync-related activities back onto the main thread. This is a documented TODO item in my TODO.md file that I never got around to doing.

On my server which has been running Heimdall since Jan 2012, I do notice the occasional exceptions from Heimdall, the most common one is related to a .flushLogs() issue that I've never devoted time to look into. It's benign from Heimdall's perspective in that despite any errors in the logs, Heimdall keeps on running just fine.

If you intend to use Heimdall on your production server, then please be aware it has rough edges because I never got a chance to finish it off (read TODO.md). So please be prepared to ignore the rough edges or possibly dive in and help fix issues as they surface; certainly the help would be appreciated and help improve the plugin for everyone else as well!

**Comment by Leopere** [comment]
I'll pass this on to @ProjectBarks
